### ISSUE TITLE
Classification section

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#1]
You have a classification section:
![image](https://user-images.githubusercontent.com/2197102/229558352-98dfdcc8-ecae-4658-8e3f-441d89ce947e.png)
This sits somewhere between a formal classification system and a textual description. I could model it as:
![image](https://user-images.githubusercontent.com/2197102/229558471-fe1efae3-c95a-4049-be82-b91263153cb0.png)
but this feels wrong in several ways. It is the classic LA "id - type - _label" structure that appears throughout, but it is missing the all-important "id" (= URL). It also misuses "type" (which is meant to be a type declared in the context document, I think) and demotes the actual data to be an explanatory label. However, in order to do better than this, I need a steer from you on the value you place on this classification data (we could just drop it), and the extent to which there is a formal ontology underpinning it, which I could refer to/use.

**Comment by RGShepherd** [comment]
> Referring to my comment elsewhere that these AAT URIs specify the 'type's of information found in that statement, I think that I prefer my approach. "Herein you will find information about the function of the artwork, or about its genre." Your approach sort of implies that the concept could form an entry under that characteristic of division - but I don't see how users or software agents could make that connection or, more importantly, do anything useful with it.

Agreed. Which means that I think this issue is now resolved.
