### ISSUE TITLE
Provenance

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#11]
> Provenances … At the moment, we can only offer fragmented data. For most works, we only have a big chunk of text (provenance.text.value). Data is also included in provenance.place, and possession.agent; but TMS has no way of joining all these up. I’ve been working on a revised structure with Gallery Systems and other TMS users, but this has stalled as the DDP has started shouting louder; we need to get it back up and running soon. I’m not sure how that can practically be mapped to an event-driven model like the CRM / Linked Art, and would welcome any suggestions for what I hope would be a temporary solution pending proper structured provenance data.

... says Rupert. I have implemented this as a LinguisticObject with a suitable classification/type:

![image](https://user-images.githubusercontent.com/2197102/231497488-4588bd19-6021-4270-aa48-6a1ad44276d3.png)

An example here of one thing that has been bugging me is that we have here in the source a bibliographic reference and a status note:

![image](https://user-images.githubusercontent.com/2197102/231498126-8236652c-a41e-412c-94b6-5dc71c450b3d.png)

Should either or both of these be mapped into the Linked Data?

**Comment by RGShepherd** [comment]
I'm happy with this for ow. If we find a burning need for the date, we'll ned to revisit it.
