### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#14]
Now we have an object with multiple titles, I assume you will want each of them to be output, using your characterization of each title as the _label.  I am further assuming that you will want to identify one title as the 'main' title, and give it the _label 'Primary Name' as per Linked Art practice, and that it is the 'full title' which will get that treatment. Here is the result for object-3798:

![image](https://user-images.githubusercontent.com/2197102/232004313-3cdfd01e-9aaf-433c-98bd-6f2c14b4c8f0.png)

**Comment by RGShepherd** [comment]
@richardofsussex , any thoughts on how to proceed so that we can resolve this one?

**Comment by richardofsussex** [comment]
I'll think about how to express your title types as a separate piece of information, and convert the _labels back to the AAT ones.

**Comment by richardofsussex** [comment]
I've switched to the AAT labels for the primary classification, then put your label as a label-only sub-classification. Unfortunately, the Madonna of the Pinks has lost all its variant titles since I last looked at it, so it isn't a good test case any more.

**Comment by RGShepherd** [comment]
Ha! That's because it transpires we're suppressing all the others on publication - previously you were working with the internal index. Let's keep the code as is, and we can review it if we decide we want to export additional titles, too. I think, then, that this is resolved for now. Thanks!
