### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#15]
Looking at measurements.description.value, I see that I have already addressed it for object-4668. This is the outcome for object-3798:

![image](https://user-images.githubusercontent.com/2197102/232010126-9c311ed9-251f-4213-8919-86ef3a03243b.png)

Is this adequate? It 'flattens' the structure, so that the description is independent of the individual measurements. This is fine so long as you only have one object in the measurements array, but would lose the correct associations if there were more than one. A more precise (but more complex) solution would be to create a part for each measurements object, with the description.value as the 'name' of that part. However, this would be less interoperable with other sets of Linked Art data. Trade-offs ...

**Comment by RGShepherd** [comment]
OK, I've been looking again at this, and at the model:
- https://linked.art/example/object/45 gives us display forms for each individual label in `dimension.identified_by.content / type:"Name"`, etc., within a child array below `dimension` which contains all the dimension data; the question is whether `identified_by` can sit as a _sibling_ of these arrays, i.e. in its own block as a child of `dimension`. If not, 
- https://linked.art/example/object/44 gives us a separate Linguistic Object in `referred_to_by.content` - as that's proposed by the model, then I think that, on reflection, I'd be happy to implement it if the previous option really wouldn't work.

**Comment by richardofsussex** [comment]
The first option doesn't work, in my view. `dimension` is an array, and you can only have one of it (this being JSON). If you have a record with two 'dimension' entries: one HxWxD and the other weight, there would be no relation between the three HxWxD values and the first display descriptor, nor between the weight value and the second one. You would also be creating a non-standard structure, which means that these labels would be harder to find.

So I think that the second option is the one to explore.

**Comment by RGShepherd** [comment]
Agreed; and that looks good to me. Resolved, I think. Thanks!
