### ISSUE TITLE
Could this repo be public?

### ISSUE THREAD

**Issue by jpadfield** [national-gallery/NG-CIIM#25]
Hi,

Given that what we are doing is not privileged or secret I was wondering when and if this repo could become public?

I am asking as it would make aspects of checking of the results and the final documentation of the work easier ...

Joe

**Comment by RGShepherd** [comment]
... and it's public.

**Comment by jpadfield** [comment]
It is great that @richardofsussex can make public URLs of the outputs, but I guess at a certain point we or other NG staff will take over this work ( unless @richardofsussex is on a retainer :-) ).

If this repo is made public we can setup exactly the same functionality by using GitHub Pages so we could have URLS like:
https://national-gallery.github.io/NG-CIIM/ciim7-output/[insert_record_id].json - and could also have a simple landing page with links on it which is automatically updated as new version of the ciim-outputs are created.

We do not need to do anything now and I can work with what we have - I was just asking as it could streamline and simplify things going forward.

So, I will re-close the discussion and we can come back to it later if needed.

**Comment by jpadfield** [comment]
> ... and it's public.

Sorry, I thought this related to Richards URLs rather than this repo.

Thanks
