### ISSUE TITLE
Munged array contents

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#3]
Where two or more arrays in the source are mapped to the same Linked Art key, the contents of each member of these arrays are merged by default, creating nonsense entries. Here is an example, now that I am mapping both bibliography and description to **referred_to_by**:
![image](https://user-images.githubusercontent.com/2197102/229574464-e004f326-396d-44e1-bf3e-bac6a10d3d2d.png)
Here the two type="LinguisticObject" members are the result of a typo in the CIIM output; the third one is the type from the first description entry. This first member of referred_to_by contains _all_ the citations (which suggests a possible way forward), plus the first description's value. The second member of referred_to_by contains a single description entry.
The 'way forward' might be to ensure that we have a two-level structure for each of these arrays, and then assign an explicit array offset to each of them. (The two-level structure design is already the case for the citations.)

**Comment by RGShepherd** [comment]
@richardofsussex, are your processing concerns now met by using XSL rather than Jolt?

The question of areas where we lack external identifiers is down to shortcomings in the TMS architecture, but can be addressed - see https://github.com/national-gallery/NG-CIIM/issues/13#issuecomment-1745011697

**Comment by richardofsussex** [comment]
Yes, thank you. I'm perfectly happy that I can do whatever you need me to do with the data, using XSLT 3.0.

**Comment by RGShepherd** [comment]
So I think, in the light of Richard's comments, we can take this issue as resolved.
