### ISSUE TITLE
Identifier

### ISSUE THREAD

**Issue by richardofsussex** [national-gallery/NG-CIIM#7]
There are six identifiers in object-4668: object number, PID, PID TMS, display number, PID (NG alternative) and system id. Which of these (if any) do you want to publish? (The PID obviously forms the basis of the whole object's URL, but that's picked up from the _id key further up.)

**Comment by RGShepherd** [comment]
Relevant data changes now listed in https://github.com/national-gallery/NG-CIIM/issues/13#issuecomment-1508320816, so I believe this is now resolved.

**Comment by RGShepherd** [comment]
@richardofsussex, we now have a series of fields in TMS which provide AAT identifiers and terms for identifier types. These will be added to the Elasticsearch in the new year, where they can be used to retrieve NG and external IDs and labels for the custodian.
